export * from "./App";
export * from "./Home"
export * from "./Landing";
export * from "./Nav";
export * from "./Choose";
export * from "./Counseller";
export * from "./Footer";
export * from "./Hero";
export * from "./Query";
export * from "./Testimonial";